import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
  `/*\n` +
  `THIS IS A GENERATED/BUNDLED FILE BY ESBUILD\n` +
  `if you want to view the source, please visit the github repository of this plugin\n` +
  `*/`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  drop: prod ? ["debugger"] : [],
});

if (prod) {
  await context.rebuild();
  console.log("Build complete.");
  process.exit(0);
} else {
  await context.watch();
}
